#!/usr/bin/env python3
"""Independent integer reference for the Kaggle 27x16 interaction engine.

The expected values written for the testbench come from this file. They are
not copied from RTL output.
"""

import os
import random

VECTOR_COUNT = 27
VECTOR_DIM = 16
PAIR_COUNT = VECTOR_COUNT * (VECTOR_COUNT - 1) // 2
RESULT_COUNT = VECTOR_DIM + PAIR_COUNT
INT16_MIN = -32768
INT16_MAX = 32767


def saturate_int16(value):
    if value > INT16_MAX:
        return INT16_MAX
    if value < INT16_MIN:
        return INT16_MIN
    return value


def quantize(accumulator, shift):
    if shift < 0 or shift >= 48:
        raise ValueError("shift out of range")
    negative = accumulator < 0
    magnitude = -accumulator if negative else accumulator
    if shift:
        magnitude += 1 << (shift - 1)
        magnitude >>= shift
    signed = -magnitude if negative else magnitude
    return saturate_int16(signed)


def pair_order():
    return [(i, j) for i in range(1, VECTOR_COUNT) for j in range(i)]


def interact(vectors, shift):
    if len(vectors) != VECTOR_COUNT:
        raise ValueError("vector count")
    pairs = pair_order()
    if len(pairs) != 351 or pairs[0] != (1, 0) or pairs[-1] != (26, 25):
        raise AssertionError("official lower-triangle order drifted")
    outputs = [int(vectors[0][element]) for element in range(VECTOR_DIM)]
    for row, column in pairs:
        total = 0
        for element in range(VECTOR_DIM):
            total += int(vectors[row][element]) * int(vectors[column][element])
        outputs.append(quantize(total, shift))
    if len(outputs) != RESULT_COUNT:
        raise AssertionError("result count")
    return outputs


def _clip_case(rows):
    clipped = []
    for row in rows:
        if len(row) != VECTOR_DIM:
            raise ValueError("dim")
        clipped.append([saturate_int16(int(value)) for value in row])
    return clipped


def blank():
    return [[0] * VECTOR_DIM for _ in range(VECTOR_COUNT)]


def pair_index(row, column):
    if not (1 <= row < VECTOR_COUNT and 0 <= column < row):
        raise ValueError("pair")
    return row * (row - 1) // 2 + column


def build_cases():
    zero = blank()
    generator = random.Random(20261008)
    random_rows = [
        [generator.randint(-200, 200) for _ in range(VECTOR_DIM)]
        for _ in range(VECTOR_COUNT)
    ]
    positive = [[INT16_MAX] * VECTOR_DIM for _ in range(VECTOR_COUNT)]
    negative = [[INT16_MIN] * VECTOR_DIM for _ in range(VECTOR_COUNT)]
    pos16 = blank()
    neg16 = blank()
    for element in range(VECTOR_DIM):
        pos16[0][element] = 3
        pos16[1][element] = 20
        neg16[0][element] = -3
        neg16[1][element] = 20
    tie_pos = blank()
    tie_pos[0][0] = 1
    tie_pos[1][0] = 1
    tie_neg = blank()
    tie_neg[0][0] = -1
    tie_neg[1][0] = 1
    tie_pos_wide = blank()
    tie_pos_wide[0][0] = 128
    tie_pos_wide[1][0] = 128
    tie_neg_wide = blank()
    tie_neg_wide[0][0] = -128
    tie_neg_wide[1][0] = 128
    order = blank()
    for index in range(VECTOR_COUNT):
        order[index][0] = index + 1
    tail = blank()
    for index in range(VECTOR_COUNT):
        tail[index][VECTOR_DIM - 1] = index - 13
    return [
        ("zero_shift0", 0, zero),
        ("random_shift0", 0, random_rows),
        ("positive_extreme_shift0", 0, positive),
        ("negative_extreme_shift0", 0, negative),
        ("pos16_products_shift0", 0, pos16),
        ("neg16_products_shift0", 0, neg16),
        ("tie_pos_shift1", 1, tie_pos),
        ("tie_neg_shift1", 1, tie_neg),
        ("tie_pos_shift15", 15, tie_pos_wide),
        ("tie_neg_shift15", 15, tie_neg_wide),
        ("zero_shift47", 47, zero),
        ("order_identity_shift0", 0, order),
        ("tail_golden_shift0", 0, tail),
    ]


def to_hex16(value):
    return "{:04x}".format(saturate_int16(value) & 0xFFFF)


def write_svh(path, cases):
    lines = [
        "// Generated by tb/ref/kaggle_interaction_c1_ref_v1.py.",
        "// Do not edit by hand.",
        "localparam integer C1_CASE_COUNT = {};".format(len(cases)),
        "localparam integer C1_VECTOR_COUNT = 27;",
        "localparam integer C1_VECTOR_DIM = 16;",
        "localparam integer C1_RESULT_COUNT = 367;",
        "logic signed [15:0] c1_vec [0:C1_CASE_COUNT-1][0:26][0:15];",
        "logic signed [15:0] c1_expected [0:C1_CASE_COUNT-1][0:366];",
        "logic [5:0] c1_shift [0:C1_CASE_COUNT-1];",
        "initial begin",
    ]
    for case_index, (name, shift, vectors) in enumerate(cases):
        expected = interact(vectors, shift)
        lines.append("  // {}".format(name))
        lines.append("  c1_shift[{}] = 6'd{};".format(case_index, shift))
        for row in range(VECTOR_COUNT):
            words = ", ".join(
                "16'h{}".format(to_hex16(vectors[row][col]))
                for col in range(VECTOR_DIM)
            )
            lines.append(
                "  c1_vec[{}][{}] = '{{{}}};".format(case_index, row, words)
            )
        for out_index in range(RESULT_COUNT):
            lines.append(
                "  c1_expected[{}][{}] = 16'h{};".format(
                    case_index, out_index, to_hex16(expected[out_index])
                )
            )
    lines.append("end")
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def self_check():
    pairs = pair_order()
    assert len(pairs) == 351
    assert pairs[0] == (1, 0)
    assert pairs[1] == (2, 0) and pairs[2] == (2, 1)
    assert pairs[pair_index(19, 4)] == (19, 4)
    assert pairs[-1] == (26, 25)
    assert pair_index(26, 25) == 350
    assert 16 + pair_index(26, 25) == 366
    zero = interact([[0] * 16 for _ in range(27)], 0)
    assert zero == [0] * 367
    assert quantize(1, 1) == 1
    assert quantize(-1, 1) == -1
    assert quantize(16384, 15) == 1
    assert quantize(-16384, 15) == -1
    assert quantize(16 * (32767 ** 2), 0) == INT16_MAX
    assert quantize(16 * ((-32768) ** 2), 0) == INT16_MAX
    assert quantize(-16 * (32767 ** 2), 0) == INT16_MIN
    cases = {name: (shift, rows) for name, shift, rows in build_cases()}
    pos16 = interact(cases["pos16_products_shift0"][1], 0)
    neg16 = interact(cases["neg16_products_shift0"][1], 0)
    assert pos16[16] == 960
    assert neg16[16] == -960
    order = interact(cases["order_identity_shift0"][1], 0)
    assert order[16] == 2
    assert order[16 + pair_index(19, 4)] == 20 * 5
    assert order[366] == 27 * 26
    tail = interact(cases["tail_golden_shift0"][1], 0)
    assert tail[366] == 156
    assert interact(cases["tie_pos_shift1"][1], 1)[16] == 1
    assert interact(cases["tie_neg_shift1"][1], 1)[16] == -1
    assert interact(cases["tie_pos_shift15"][1], 15)[16] == 1
    assert interact(cases["tie_neg_shift15"][1], 15)[16] == -1
    assert interact(cases["positive_extreme_shift0"][1], 0)[16] == INT16_MAX
    assert interact(cases["negative_extreme_shift0"][1], 0)[0] == INT16_MIN
    assert interact(cases["negative_extreme_shift0"][1], 0)[16] == INT16_MAX


def main():
    self_check()
    print("CONTRACT=B")
    print("BOTTOM_INDEX=0..15")
    print("INTERACTION_INDEX=16..366")
    print("LAST_PAIR=(26,25)")
    print("LAST_PAIR_INDEX=350")
    print("LAST_OUTPUT_INDEX=366")
    print("GOLDEN_VALUE_26_25=156")
    print("GOLDEN_NOTE=156 is the tail-case dot product, not a pair index")
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    destination = os.path.join(root, "generated", "kaggle_c1_cases_v1.svh")
    write_svh(destination, [
        (name, shift, _clip_case(rows))
        for name, shift, rows in build_cases()
    ])
    print("wrote {}".format(destination))


if __name__ == "__main__":
    main()
