#!/usr/bin/env python3
"""Generate a deterministic trained-and-quantized Stage 2L F37X MLP package.

The generated model is a compact 16 -> 16 -> 8 -> 2 classifier. It is
trained with a small NumPy Adam loop on a deterministic nonlinear synthetic
classification task, then quantized to the exact F37X integer contract:

* signed INT16 activations
* signed INT8 weights
* signed INT24 biases
* signed 48-bit accumulator (the generated model remains far inside range)
* power-of-two output shift with round-to-nearest, ties away from zero
* signed INT16 saturation
* ReLU on hidden layers

The binary package includes layers, test inputs, labels, and exact integer
software-reference outputs. A JSON manifest records provenance and accuracy.
No external ML framework is required beyond NumPy.
"""

import argparse
import hashlib
import json
import math
import struct
from pathlib import Path

import numpy as np

MAGIC = b"F37XMPK1"
FORMAT_VERSION = 1
HEADER_BYTES = 64
FLAGS_LABELS = 1 << 0
FLAGS_EXPECTED_OUTPUTS = 1 << 1
INPUT_SCALE = 16
MAX_LAYERS = 4
MAX_WEIGHT_VALUES = 65536
MAX_BIAS_VALUES = 1024
ACC_LIMIT = 1 << 47

HEADER_STRUCT = struct.Struct("<8sIIIIIIIIQQQ")
LAYER_STRUCT = struct.Struct("<IIIIIIII")


class QuantizedLayer(object):
    def __init__(
        self,
        weights,
        biases,
        output_shift,
        relu,
        weight_scale,
        weight_base,
        bias_base,
    ):
        self.weights = weights
        self.biases = biases
        self.output_shift = int(output_shift)
        self.relu = bool(relu)
        self.weight_scale = int(weight_scale)
        self.weight_base = int(weight_base)
        self.bias_base = int(bias_base)

    @property
    def in_dim(self):
        return int(self.weights.shape[1])

    @property
    def out_dim(self):
        return int(self.weights.shape[0])


class Dataset(object):
    def __init__(
        self,
        x_train_float,
        y_train,
        x_train_int16,
        x_test_float,
        y_test,
        x_test_int16,
    ):
        self.x_train_float = x_train_float
        self.y_train = y_train
        self.x_train_int16 = x_train_int16
        self.x_test_float = x_test_float
        self.y_test = y_test
        self.x_test_int16 = x_test_int16


def fnv1a64(data):
    value = 0xCBF29CE484222325
    for byte in data:
        if not isinstance(byte, int):
            byte = ord(byte)
        value ^= byte
        value = (value * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return value


def round_ties_away_from_zero(values, shift):
    values64 = np.asarray(values, dtype=np.int64)
    if shift == 0:
        return values64.copy()
    magnitude = np.abs(values64)
    rounded = (magnitude + (1 << (shift - 1))) >> shift
    return np.where(values64 < 0, -rounded, rounded)


def integer_inference(inputs, layers):
    activations = np.asarray(inputs, dtype=np.int64)
    layer_accumulators = []
    layer_outputs = []

    for layer in layers:
        accumulators = (
            np.dot(activations, layer.weights.astype(np.int64).T)
            + layer.biases.astype(np.int64)
        )
        if np.any(accumulators <= -ACC_LIMIT) or np.any(
            accumulators >= ACC_LIMIT
        ):
            raise RuntimeError(
                "generated model exceeds signed 48-bit accumulator range"
            )

        outputs = round_ties_away_from_zero(
            accumulators, layer.output_shift
        )
        outputs = np.clip(outputs, -32768, 32767)
        if layer.relu:
            outputs = np.maximum(outputs, 0)

        layer_accumulators.append(accumulators.copy())
        layer_outputs.append(outputs.astype(np.int16))
        activations = outputs.astype(np.int64)

    return layer_accumulators, layer_outputs


def make_dataset(seed, train_count, test_count):
    rng = np.random.RandomState(seed)
    total_count = train_count + test_count
    raw = rng.normal(0.0, 1.0, size=(total_count, 16)).astype(np.float64)
    raw = np.clip(raw, -3.0, 3.0)

    # Independent nonlinear rule; labels are not generated by the trained MLP.
    score = (
        1.15 * raw[:, 0]
        - 0.95 * raw[:, 1]
        + 0.65 * raw[:, 2]
        + 0.55 * raw[:, 3]
        + 0.85 * np.maximum(raw[:, 4] + 0.70 * raw[:, 5], 0.0)
        - 0.75 * np.maximum(raw[:, 6] - 0.80 * raw[:, 7], 0.0)
        + 0.55 * raw[:, 8] * raw[:, 9]
        - 0.45 * raw[:, 10] * raw[:, 11]
        + 0.35 * np.maximum(-raw[:, 12] + raw[:, 13], 0.0)
        + 0.25 * raw[:, 14]
        - 0.20 * raw[:, 15]
    )
    threshold = float(np.median(score[:train_count]))
    labels = (score > threshold).astype(np.int64)

    quantized = np.clip(
        np.rint(raw * INPUT_SCALE), -32768, 32767
    ).astype(np.int16)
    dequantized = quantized.astype(np.float64) / float(INPUT_SCALE)

    return Dataset(
        dequantized[:train_count],
        labels[:train_count],
        quantized[:train_count],
        dequantized[train_count:],
        labels[train_count:],
        quantized[train_count:],
    )


def train_float_mlp(dataset, seed, epochs, learning_rate):
    rng = np.random.RandomState(seed)
    dimensions = [16, 16, 8, 2]
    weights = []
    biases = []

    for in_dim, out_dim in zip(dimensions[:-1], dimensions[1:]):
        weights.append(
            rng.normal(
                0.0,
                math.sqrt(2.0 / float(in_dim)),
                size=(out_dim, in_dim),
            ).astype(np.float64)
        )
        biases.append(np.zeros(out_dim, dtype=np.float64))

    first_moment_w = [np.zeros_like(value) for value in weights]
    second_moment_w = [np.zeros_like(value) for value in weights]
    first_moment_b = [np.zeros_like(value) for value in biases]
    second_moment_b = [np.zeros_like(value) for value in biases]

    beta1 = 0.9
    beta2 = 0.999
    epsilon = 1.0e-8
    l2_penalty = 1.0e-4
    batch_size = 128
    step = 0

    x_train = dataset.x_train_float
    y_train = dataset.y_train

    for _epoch in range(epochs):
        order = rng.permutation(x_train.shape[0])

        for start in range(0, x_train.shape[0], batch_size):
            selection = order[start : start + batch_size]
            inputs = x_train[selection]
            labels = y_train[selection]

            z1 = np.dot(inputs, weights[0].T) + biases[0]
            a1 = np.maximum(z1, 0.0)
            z2 = np.dot(a1, weights[1].T) + biases[1]
            a2 = np.maximum(z2, 0.0)
            logits = np.dot(a2, weights[2].T) + biases[2]

            shifted = logits - np.max(logits, axis=1, keepdims=True)
            exponentials = np.exp(shifted)
            probabilities = exponentials / np.sum(
                exponentials, axis=1, keepdims=True
            )

            grad_logits = probabilities
            grad_logits[np.arange(labels.size), labels] -= 1.0
            grad_logits /= float(labels.size)

            grad_w2 = np.dot(grad_logits.T, a2) + l2_penalty * weights[2]
            grad_b2 = np.sum(grad_logits, axis=0)
            grad_a2 = np.dot(grad_logits, weights[2])
            grad_z2 = grad_a2 * (z2 > 0.0)

            grad_w1 = np.dot(grad_z2.T, a1) + l2_penalty * weights[1]
            grad_b1 = np.sum(grad_z2, axis=0)
            grad_a1 = np.dot(grad_z2, weights[1])
            grad_z1 = grad_a1 * (z1 > 0.0)

            grad_w0 = np.dot(grad_z1.T, inputs) + l2_penalty * weights[0]
            grad_b0 = np.sum(grad_z1, axis=0)

            grad_weights = [grad_w0, grad_w1, grad_w2]
            grad_biases = [grad_b0, grad_b1, grad_b2]
            step += 1

            for index in range(len(weights)):
                first_moment_w[index] = (
                    beta1 * first_moment_w[index]
                    + (1.0 - beta1) * grad_weights[index]
                )
                second_moment_w[index] = (
                    beta2 * second_moment_w[index]
                    + (1.0 - beta2) * np.square(grad_weights[index])
                )
                first_moment_b[index] = (
                    beta1 * first_moment_b[index]
                    + (1.0 - beta1) * grad_biases[index]
                )
                second_moment_b[index] = (
                    beta2 * second_moment_b[index]
                    + (1.0 - beta2) * np.square(grad_biases[index])
                )

                correction1 = 1.0 - beta1 ** step
                correction2 = 1.0 - beta2 ** step
                corrected_mw = first_moment_w[index] / correction1
                corrected_vw = second_moment_w[index] / correction2
                corrected_mb = first_moment_b[index] / correction1
                corrected_vb = second_moment_b[index] / correction2

                weights[index] -= learning_rate * corrected_mw / (
                    np.sqrt(corrected_vw) + epsilon
                )
                biases[index] -= learning_rate * corrected_mb / (
                    np.sqrt(corrected_vb) + epsilon
                )

    def predict(values):
        hidden1 = np.maximum(
            np.dot(values, weights[0].T) + biases[0], 0.0
        )
        hidden2 = np.maximum(
            np.dot(hidden1, weights[1].T) + biases[1], 0.0
        )
        output = np.dot(hidden2, weights[2].T) + biases[2]
        return np.argmax(output, axis=1)

    train_accuracy = float(
        np.mean(predict(dataset.x_train_float) == dataset.y_train)
    )
    test_accuracy = float(
        np.mean(predict(dataset.x_test_float) == dataset.y_test)
    )
    return weights, biases, train_accuracy, test_accuracy


def quantize_layers(float_weights, float_biases):
    layers = []
    weight_base = 0
    bias_base = 0

    for index, values in enumerate(zip(float_weights, float_biases)):
        weights, biases = values
        max_abs_weight = float(np.max(np.abs(weights)))
        if max_abs_weight == 0.0:
            scale_power = 6
        else:
            scale_power = int(
                math.floor(math.log(127.0 / max_abs_weight, 2.0))
            )
            scale_power = max(0, min(6, scale_power))

        weight_scale = 1 << scale_power
        quantized_weights = np.clip(
            np.rint(weights * weight_scale), -128, 127
        ).astype(np.int8)
        quantized_biases = np.rint(
            biases * INPUT_SCALE * weight_scale
        ).astype(np.int64)

        if np.any(quantized_biases < -8388608) or np.any(
            quantized_biases > 8388607
        ):
            raise RuntimeError("quantized bias exceeds signed INT24")

        layer = QuantizedLayer(
            quantized_weights,
            quantized_biases.astype(np.int32),
            scale_power,
            index + 1 < len(float_weights),
            weight_scale,
            weight_base,
            bias_base,
        )
        layers.append(layer)
        weight_base += layer.in_dim * layer.out_dim
        bias_base += layer.out_dim

    if len(layers) > MAX_LAYERS:
        raise RuntimeError("model exceeds F37X MAX_LAYERS")
    if weight_base > MAX_WEIGHT_VALUES:
        raise RuntimeError("model exceeds F37X weight memory")
    if bias_base > MAX_BIAS_VALUES:
        raise RuntimeError("model exceeds F37X bias memory")

    return layers


def pad_to_4(payload):
    while len(payload) % 4 != 0:
        payload.append(0)


def vector_to_list(values):
    return [int(value) for value in np.asarray(values).reshape(-1)]


def build_package(
    model_name,
    layers,
    inputs,
    labels,
    expected_outputs,
):
    name_bytes = model_name.encode("utf-8")
    payload = bytearray(name_bytes)

    for layer in layers:
        payload += LAYER_STRUCT.pack(
            layer.in_dim,
            layer.out_dim,
            layer.output_shift,
            int(layer.relu),
            layer.in_dim * layer.out_dim,
            layer.out_dim,
            layer.weight_base,
            layer.bias_base,
        )
        payload += layer.weights.astype("<i1", copy=False).tobytes(order="C")
        pad_to_4(payload)
        payload += layer.biases.astype("<i4", copy=False).tobytes(order="C")

    for sample_index in range(inputs.shape[0]):
        payload += struct.pack(
            "<II", sample_index, int(labels[sample_index])
        )
        payload += inputs[sample_index].astype("<i2", copy=False).tobytes()
        payload += expected_outputs[sample_index].astype(
            "<i2", copy=False
        ).tobytes()

    payload_bytes = bytes(payload)
    payload_hash = fnv1a64(payload_bytes)
    header = HEADER_STRUCT.pack(
        MAGIC,
        FORMAT_VERSION,
        HEADER_BYTES,
        len(layers),
        int(inputs.shape[0]),
        int(inputs.shape[1]),
        int(expected_outputs.shape[1]),
        FLAGS_LABELS | FLAGS_EXPECTED_OUTPUTS,
        len(name_bytes),
        len(payload_bytes),
        payload_hash,
        0,
    )
    if len(header) != HEADER_BYTES:
        raise AssertionError("package header size mismatch")
    return header + payload_bytes, payload_hash


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--seed", type=int, default=20260724)
    parser.add_argument("--train-seed", type=int, default=123)
    parser.add_argument("--train-count", type=int, default=2048)
    parser.add_argument("--test-count", type=int, default=256)
    parser.add_argument("--epochs", type=int, default=500)
    parser.add_argument("--learning-rate", type=float, default=0.01)
    parser.add_argument(
        "--minimum-quantized-accuracy", type=float, default=0.88
    )
    return parser.parse_args()


def main():
    args = parse_args()
    if args.train_count < 256 or args.test_count < 32:
        raise ValueError("dataset sizes are too small")

    dataset = make_dataset(args.seed, args.train_count, args.test_count)
    values = train_float_mlp(
        dataset,
        args.train_seed,
        args.epochs,
        args.learning_rate,
    )
    float_weights, float_biases, float_train_accuracy, float_test_accuracy = (
        values
    )
    layers = quantize_layers(float_weights, float_biases)

    _, train_layer_outputs = integer_inference(
        dataset.x_train_int16, layers
    )
    test_accumulators, test_layer_outputs = integer_inference(
        dataset.x_test_int16, layers
    )
    quantized_train_predictions = np.argmax(
        train_layer_outputs[-1], axis=1
    )
    quantized_test_predictions = np.argmax(
        test_layer_outputs[-1], axis=1
    )
    quantized_train_accuracy = float(
        np.mean(quantized_train_predictions == dataset.y_train)
    )
    quantized_test_accuracy = float(
        np.mean(quantized_test_predictions == dataset.y_test)
    )

    if quantized_test_accuracy < args.minimum_quantized_accuracy:
        raise RuntimeError(
            "quantized test accuracy below threshold: "
            "%.6f < %.6f"
            % (quantized_test_accuracy, args.minimum_quantized_accuracy)
        )

    model_name = "stage2l_trained_quantized_classifier_16x16x8x2"
    package, payload_hash = build_package(
        model_name,
        layers,
        dataset.x_test_int16,
        dataset.y_test,
        test_layer_outputs[-1],
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(package)
    package_sha256 = hashlib.sha256(package).hexdigest()

    manifest_layers = []
    for index, layer in enumerate(layers):
        manifest_layers.append(
            {
                "index": index,
                "in_dim": layer.in_dim,
                "out_dim": layer.out_dim,
                "output_shift": layer.output_shift,
                "relu": layer.relu,
                "weight_scale": layer.weight_scale,
                "weight_base": layer.weight_base,
                "bias_base": layer.bias_base,
                "weight_count": layer.in_dim * layer.out_dim,
                "bias_count": layer.out_dim,
                "weight_min": int(np.min(layer.weights)),
                "weight_max": int(np.max(layer.weights)),
                "bias_min": int(np.min(layer.biases)),
                "bias_max": int(np.max(layer.biases)),
                "max_abs_test_accumulator": int(
                    np.max(np.abs(test_accumulators[index]))
                ),
            }
        )

    quantized_correct = int(
        np.sum(quantized_test_predictions == dataset.y_test)
    )
    manifest = {
        "format": "F37XMPK1",
        "format_version": FORMAT_VERSION,
        "model_name": model_name,
        "architecture": [16, 16, 8, 2],
        "input_scale": INPUT_SCALE,
        "dataset": {
            "kind": "deterministic_nonlinear_synthetic_binary_classification",
            "label_source": "independent_nonlinear_rule",
            "seed": args.seed,
            "train_count": args.train_count,
            "test_count": args.test_count,
            "test_class_counts": {
                "0": int(np.sum(dataset.y_test == 0)),
                "1": int(np.sum(dataset.y_test == 1)),
            },
        },
        "training": {
            "method": "numpy_adam_float_mlp",
            "seed": args.train_seed,
            "epochs": args.epochs,
            "learning_rate": args.learning_rate,
            "float_train_accuracy": float_train_accuracy,
            "float_test_accuracy": float_test_accuracy,
        },
        "quantization": {
            "activation_type": "signed_int16",
            "weight_type": "signed_int8",
            "bias_type": "signed_int24",
            "accumulator_type": "signed_int48",
            "activation_scale": INPUT_SCALE,
            "rounding": "nearest_ties_away_from_zero",
            "saturation": "signed_int16",
            "hidden_activation": "relu",
            "quantized_train_accuracy": quantized_train_accuracy,
            "quantized_test_accuracy": quantized_test_accuracy,
            "quantized_test_correct": quantized_correct,
        },
        "package": {
            "path": str(args.output),
            "bytes": len(package),
            "sha256": package_sha256,
            "payload_fnv1a64": "0x%016x" % payload_hash,
            "sample_count": args.test_count,
            "input_dim": 16,
            "output_dim": 2,
            "expected_output_values": args.test_count * 2,
        },
        "layers": manifest_layers,
        "reference_examples": [
            {
                "sample_index": index,
                "label": int(dataset.y_test[index]),
                "input": vector_to_list(dataset.x_test_int16[index]),
                "expected_output": vector_to_list(test_layer_outputs[-1][index]),
                "prediction": int(quantized_test_predictions[index]),
            }
            for index in range(min(5, args.test_count))
        ],
    }
    args.manifest.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print("STAGE2L_MODEL_PACKAGE_GENERATED")
    print("MODEL_NAME=%s" % model_name)
    print("ARCHITECTURE=16,16,8,2")
    print("TRAIN_SAMPLES=%d" % args.train_count)
    print("TEST_SAMPLES=%d" % args.test_count)
    print("FLOAT_TRAIN_ACCURACY=%.6f" % float_train_accuracy)
    print("FLOAT_TEST_ACCURACY=%.6f" % float_test_accuracy)
    print("QUANTIZED_TRAIN_ACCURACY=%.6f" % quantized_train_accuracy)
    print("QUANTIZED_TEST_ACCURACY=%.6f" % quantized_test_accuracy)
    print("QUANTIZED_TEST_CORRECT=%d" % quantized_correct)
    print("PACKAGE=%s" % args.output)
    print("PACKAGE_BYTES=%d" % len(package))
    print("PACKAGE_SHA256=%s" % package_sha256)
    print("PAYLOAD_FNV1A64=0x%016x" % payload_hash)
    print("MANIFEST=%s" % args.manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
