"""Generate reproducible software-only embedding trace feasibility evidence."""

import argparse
import json
import platform
from pathlib import Path

import numpy as np

from analysis.channel_mapping import simulate_channel_schedule
from analysis.embedding_trace import analyze_trace, build_embedding_trace, load_trace, save_trace
from analysis.request_coalescing import CoalescerConfig, simulate_coalescing
from model.data import generate_synthetic_dataset, load_criteo_tsv
from model.data.synthetic_dataset import TRACE_MODES
from model.dlrm.config import DLRMConfig


def _markdown(summary):
    lines = [
        "# Embedding trace feasibility report", "",
        "This report is generated by `analysis/run_trace_feasibility.py`. The current",
        "evidence source is **{}**. Synthetic traces validate reproducibility and tool".format(summary["evidence_source"]),
        "behavior only; they do not establish a thesis result or pass GATE-T1/T2/T3.", "",
        "## Gate status", "",
        "| Gate | Status | Reason |", "|---|---|---|",
    ]
    for gate, value in summary["gates"].items():
        lines.append("| {} | {} | {} |".format(gate, value["status"], value["reason"]))
    lines += ["", "## Synthetic scenario summary", "",
              "| Scenario | W=8 duplicate ratio | dual read reduction | dual average wait | dual P99 wait |",
              "|---|---:|---:|---:|---:|"]
    for name, result in summary["scenarios"].items():
        stats = result["trace_statistics"]["windows"]["8"]
        dual = result["coalescing"]["dual"]
        lines.append("| {} | {:.4f} | {:.4f} | {:.3f} | {:.3f} |".format(
            name, stats["duplicate_ratio"], dual["read_reduction_ratio"],
            dual["wait_time"]["average"], dual["wait_time"]["p99"]
        ))
    lines += ["", "The project's 10%-15% read-reduction range is an internal engineering",
              "review line, not a universal academic threshold. Synthetic rows cannot satisfy it",
              "for gate approval. The JSON summary also records a 7x7 dual-constraint sweep",
              "over request-count and wait bounds for every scenario.", "", "## Abstract 8-channel comparison", "",
              "| Scenario | modulo max/mean | table-static max/mean | queue-aware completion improvement | four-way combined improvement |",
              "|---|---:|---:|---:|---:|"]
    for name, result in summary["scenarios"].items():
        channel = result["channel_scheduling"]["8"]
        lines.append("| {} | {:.3f} | {:.3f} | {:.4f} | {:.4f} |".format(
            name,
            channel["modulo"]["request_imbalance_max_over_mean"],
            channel["static_table"]["request_imbalance_max_over_mean"],
            channel["queue_aware_improvement"]["completion_cycle_reduction_ratio"],
            channel["gate_t3_four_way"]["combined_cycle_reduction_ratio"],
        ))
    lines += ["", "## Channel-model boundary", "",
              "The channel results use an abstract fixed-service model. Queue-aware policies",
              "assume two candidate placements. No value is a physical F37X HBM address map,",
              "RTL timing result, or proof that provider bandwidth is achievable.", "",
              "## Required next evidence", "",
              "Provide a local Criteo TSV file or directory. Re-run with `--criteo-path`; then",
              "review the real duplicate/locality statistics before setting coalescing windows,",
              "state bounds, or a channel policy. Gate approval remains a human decision.", ""]
    return "\n".join(lines)


def _scenario(config, name, dataset, trace_dir):
    trace = build_embedding_trace(dataset["categorical_ids"], config.batch_size, 1.0, 8)
    roundtrip = {}
    for suffix in ("jsonl", "csv", "npy"):
        path = trace_dir / "{}_embedding_trace.{}".format(name, suffix)
        save_trace(trace, path)
        loaded = load_trace(path)
        roundtrip[suffix] = {
            "status": "PASS" if loaded == trace else "FAIL",
            "record_count": len(loaded), "path": str(path.resolve()),
        }
    stats = analyze_trace(trace)
    coalescing = {}
    dual_entries = None
    for policy in ("none", "fixed_count", "fixed_time", "dual", "adaptive"):
        report, entries = simulate_coalescing(trace, CoalescerConfig(policy=policy))
        coalescing[policy] = report
        if policy == "dual":
            dual_entries = entries
    baseline_throughput = coalescing["none"]["estimated_request_throughput"]
    for report in coalescing.values():
        report["estimated_throughput_change_ratio"] = (
            report["estimated_request_throughput"] / baseline_throughput - 1.0
            if baseline_throughput else None
        )
    dual_sweep = {}
    for max_requests in (1, 2, 4, 8, 16, 32, 64):
        for max_wait in (1.0, 2.0, 4.0, 8.0, 16.0, 32.0, 64.0):
            sweep_report, _ = simulate_coalescing(
                trace, CoalescerConfig(
                    policy="dual", max_requests=max_requests, max_wait=max_wait,
                    max_unique=max(256, max_requests * config.num_tables),
                )
            )
            dual_sweep["requests_{}_wait_{}".format(max_requests, int(max_wait))] = {
                "read_reduction_ratio": sweep_report["read_reduction_ratio"],
                "average_added_wait": sweep_report["wait_time"]["average"],
                "p95_added_wait": sweep_report["wait_time"]["p95"],
                "p99_added_wait": sweep_report["wait_time"]["p99"],
                "maximum_added_wait": sweep_report["wait_time"]["maximum"],
                "estimated_state_bytes": sweep_report["estimated_state_bytes"],
            }
    channels = {}
    for channel_count in (4, 8, 16, 32):
        reports = {
            scheduler: simulate_channel_schedule(dual_entries, channel_count, scheduler)
            for scheduler in (
                "modulo", "static_table", "per_channel_fifo_rr", "queue_aware", "age_queue"
            )
        }
        static_completion = reports["modulo"]["estimated_completion_cycles"]
        queue_completion = reports["queue_aware"]["estimated_completion_cycles"]
        reports["queue_aware_improvement"] = {
            "completion_cycle_reduction_ratio": (
                (static_completion - queue_completion) / static_completion
                if static_completion else 0.0
            ),
            "max_over_mean_reduction": (
                reports["modulo"]["request_imbalance_max_over_mean"]
                - reports["queue_aware"]["request_imbalance_max_over_mean"]
            ),
        }
        no_opt = simulate_channel_schedule(trace, channel_count, "modulo")
        only_schedule = simulate_channel_schedule(trace, channel_count, "queue_aware")
        reports["gate_t3_four_way"] = {
            "no_optimization_cycles": no_opt["estimated_completion_cycles"],
            "coalescing_only_cycles": reports["modulo"]["estimated_completion_cycles"],
            "scheduling_only_cycles": only_schedule["estimated_completion_cycles"],
            "coalescing_plus_scheduling_cycles": queue_completion,
            "combined_cycle_reduction_ratio": (
                (no_opt["estimated_completion_cycles"] - queue_completion)
                / no_opt["estimated_completion_cycles"]
                if no_opt["estimated_completion_cycles"] else 0.0
            ),
        }
        channels[str(channel_count)] = reports
    return {
        "dataset_metadata": dataset["metadata"], "trace_roundtrip": roundtrip,
        "trace_statistics": stats, "coalescing": coalescing,
        "gate_t1_dual_constraint_sweep": dual_sweep,
        "channel_scheduling": channels,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="config/dlrm_software_config.json")
    parser.add_argument("--criteo-path")
    parser.add_argument("--max-samples", type=int, default=128)
    parser.add_argument("--output", default="results/trace_feasibility_summary.json")
    parser.add_argument("--report", default="docs/trace_feasibility_report.md")
    parser.add_argument("--trace-dir", default="results/traces")
    args = parser.parse_args()
    config = DLRMConfig.load(args.config)
    trace_dir = Path(args.trace_dir)
    trace_dir.mkdir(parents=True, exist_ok=True)
    scenarios = {}
    if args.criteo_path:
        dataset = load_criteo_tsv(
            args.criteo_path, config, args.max_samples, map_to_table_sizes=False
        )
        scenarios["criteo_local"] = _scenario(config, "criteo_local", dataset, trace_dir)
        evidence_source = "real user-supplied local Criteo"
        gate_status = "READY_FOR_HUMAN_REVIEW"
        gate_reason = "real local trace analyzed; thresholds and approval require review"
    else:
        for mode in TRACE_MODES:
            dataset = generate_synthetic_dataset(config, args.max_samples, mode)
            scenarios[mode] = _scenario(config, mode, dataset, trace_dir)
        evidence_source = "deterministic synthetic traces"
        gate_status = "INCONCLUSIVE"
        gate_reason = "real user-supplied Criteo trace is absent"
    summary = {
        "status": "PASS",
        "scope": "software trace/coalescing/channel feasibility tooling",
        "evidence_source": evidence_source,
        "environment": {"python": platform.python_version(), "numpy": np.__version__},
        "gates": {
            gate: {"status": gate_status, "passed": False, "reason": gate_reason}
            for gate in ("GATE-T1", "GATE-T2", "GATE-T3")
        },
        "scenarios": scenarios,
        "claim_boundary": (
            "synthetic scenarios are tooling validation only" if not args.criteo_path
            else "real trace analyzed but no gate is auto-approved"
        ),
    }
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    report = Path(args.report)
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(_markdown(summary), encoding="utf-8")
    print(json.dumps({
        "status": summary["status"], "evidence_source": evidence_source,
        "gates": summary["gates"], "output": str(output.resolve()),
        "report": str(report.resolve()),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
